# Nama workflow yang akan tampil di tab Actions GitHub
name: Deploy to VPS

# Pemicu (trigger) workflow
on:
  push:
    branches:
      - main # Ganti dengan 'master' jika branch utama Anda master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        # Gunakan versi rilis yang stabil, bukan @master
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Masuk ke direktori project di VPS Anda
            cd /var/www/faaroti.shop/faaroti/

            # Tarik perubahan terbaru dari branch main
            git pull origin main

            echo "Code pulled successfully."

            # ------------------------------------------------------------------
            # !!! PENTING: UNCOMMENT DAN SESUAIKAN BAGIAN DI BAWAH INI !!!
            # Setelah kode diperbarui, aplikasi Anda perlu di-restart agar
            # perubahan bisa aktif. Pilih yang sesuai dengan project Anda.
            # ------------------------------------------------------------------

            # Contoh untuk project PHP/Laravel (jika menggunakan FPM)
            # echo "Restarting PHP-FPM..."
            # sudo systemctl restart php8.2-fpm

            # Contoh untuk project Node.js (jika menggunakan PM2)
            # echo "Restarting Node.js application..."
            # pm2 restart nama_aplikasi_anda

            # Contoh untuk project Python (jika menggunakan Gunicorn/Systemd)
            # echo "Restarting Gunicorn service..."
            # sudo systemctl restart gunicorn

            echo "Deployment complete! ✅"
